name: eClassify
description: A classified app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev [Be careful]

version: 1.1.0+12

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.19.1
  firebase_messaging: ^14.8.1
  flick_video_player: ^0.8.0
  youtube_player_flutter: ^9.0.0
  country_picker: ^2.0.25
  connectivity_plus: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  flutter_bloc: ^8.1.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  url_launcher: ^6.2.5
  flutter_html: ^3.0.0-beta.2
  share_plus: ^9.0.0
  in_app_review: ^2.0.8
  lottie: ^3.0.0
  mime_type: ^1.0.0
  awesome_notifications: ^0.9.3+1
  device_preview: ^1.1.0
  path_provider: ^2.1.2
  record: ^5.1.1
  audioplayers: ^6.0.0
  image_cropper: ^4.0.1
  permission_handler: ^11.3.0
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  hydrated_bloc: ^9.1.4
  label_marker: ^1.0.1
  flutter_typeahead: ^5.2.0
  any_link_preview: ^3.0.0
  geocoding: ^3.0.0
  encrypt: ^5.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  geolocator: ^12.0.0
  flutter_svg: ^2.0.9
  #uni_links: ^0.5.1
  #google_maps_webservice: ^0.0.19
  google_mobile_ads: ^5.0.0
  flutter_image_compress: ^2.2.0
  google_maps_flutter: ^2.6.1
  vibration: ^1.8.4
  device_region: ^1.4.0
  flutter_pdfview: ^1.3.2
  app_links: ^6.1.1
  change_app_package_name: ^1.1.0
  video_player: ^2.8.6
  path: ^1.9.0
  #payment gateways
  flutter_stripe: ^10.1.1
  in_app_purchase: ^3.1.13
  #flutter_paystack: ^1.0.7
  razorpay_flutter: ^1.3.7
  #pay_with_paystack:


dependency_overrides:
  intl: ^0.17.0
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master



dev_dependencies:
  rename: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/onboardings/
    - assets/svg/bottomnav/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/Logo/
    - assets/svg/Illustrators/
    - assets/svg/payment/


  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
